---
title: "KJ?"
author: "Jake Rozran"
date: "2022-10-20"
output: html_document
---

```{r setup, include = FALSE}
# LIBRARIES
source("01_hk_libraries.R")

# DATA REFRESH
system("python whoop.py")

# DATA SOURCE FUNCTIONS
source("02_hk_data_functions.R")

# GET WORKOUTS DATA
workouts <- get_workouts_data() %>% 
    mutate(wo_len = wo_end - wo_start,
           kj_per_min = kilojoules / as.numeric(wo_len))

workouts %>% 
    filter(name == "Running")

ggplot(workouts, aes(x = date, y = kj_per_min)) + 
    geom_point() +
    facet_wrap(~ name)
```

```{r strava}
library(rStrava)
library(httr)
library(lubridate)
library(dplyr)
library(tidyr)
library(tibble)

options(scipen = 999)

stoken <- config(token = readRDS("../.httr-oauth")[[2]])

me <- get_athlete(stoken)
activities <- get_activity_list(id = NULL, 
                                stoken = stoken, 
                                before = NULL,
                                after = NULL)

act_df <- tibble(list = activities) %>% 
    hoist(list, 
          name = "name", 
          distance = "distance",
          total_elevation_gain = "total_elevation_gain",
          moving_time = "moving_time",
          elapsed_time = "elapsed_time",
          sport_type = "sport_type",
          id = "id",
          start_date = "start_date",
          start_date_local = "start_date_local",
          timezone = "timezone",
          utc_offset = "utc_offset",
          location_city = "location_city",
          location_state = "location_state",
          location_country = "location_country",
          trainer = "trainer",
          average_speed = "average_speed", 
          max_speed = "max_speed",
          has_heartrate = "has_heartrate",
          average_heartrate = "average_heartrate",
          max_heartrate = "max_heartrate") %>% 
    select(-list) %>% 
    mutate(moving_time_min = moving_time / 60,
           elapsed_time_min = elapsed_time / 60,
           distance_miles = distance / 1609.344,
           elevation_miles = total_elevation_gain / 1609.344,
           avg_speed_mph = average_speed * 2.236936,
           max_speed_mph = max_speed * 2.236936,
           datetime = as_datetime(start_date_local, 
                                  format = "%Y-%m-%dT%H:%M:%SZ"),
           date = as_date(datetime))

runs <- act_df %>% 
    filter(sport_type == "Run") %>% 
    group_by(date) %>% 
    summarise(moving_time_min = sum(moving_time_min),
              elapsed_time_min = sum(elapsed_time_min),
              distance_miles = sum(distance_miles),
              elevation_miles = sum(elevation_miles),
              treadmill = sum(trainer) / length(date)) %>% 
    mutate(avg_speed_mph = distance_miles / moving_time_min * 60,
           avg_elev_mph = elevation_miles / moving_time_min * 60) %>% 
    filter(date != as_date("2018-10-24"))


```

I have distance, speed, elevation, moving time, elapsed time, treadmill, 

distance + speed removes the need for avg_speed and moving_time. Distance and 
speed basically account for this. 

So... distance + speed + elevation + treadmill. 

```{r run_hist}
ggplot(runs, aes(x = distance_miles)) + 
    geom_histogram()

ggplot(runs, aes(x = moving_time_min)) + 
    geom_histogram()

ggplot(runs, aes(x = elevation_miles)) + 
    geom_histogram()

ggplot(runs, aes(x = avg_speed_mph)) + 
    geom_histogram()

ggplot(runs, aes(x = treadmill)) + 
    geom_bar()

```

```{r run_plot}
ggplot(runs, aes(x = distance_miles, y = elevation_miles)) + 
    geom_point() + 
    facet_wrap(~ treadmill)

ggplot(runs, aes(x = date, y = avg_speed_mph)) + 
    geom_point() +
    geom_smooth()

ggplot(runs, aes(x = date, y = distance_miles)) +
    geom_point() + 
    geom_smooth()

stand_runs <- runs %>%
    filter(avg_speed_mph >= 4.5) %>% 
    arrange(desc(date)) %>% 
    mutate(dist_norm = (distance_miles - min(distance_miles)) / 
               (max(distance_miles) - min(distance_miles)),
           elev_norm = (elevation_miles - min(elevation_miles)) / 
               (max(elevation_miles) - min(elevation_miles)),
           mph_norm = (avg_speed_mph - min(avg_speed_mph)) / 
               (max(avg_speed_mph) - min(avg_speed_mph)),
           score = (dist_norm + elev_norm + mph_norm) * ifelse(treadmill == 1, 0.9, 1)) %>% 
    select(date,
           score,
           dist_norm,
           elev_norm,
           mph_norm,
           treadmill)

wrun <- workouts %>% 
    filter(name == "Running") %>% 
    select(date, 
           intensity_score,
           raw_intensity_score,
           kilojoules,
           calories,
           max_heart_rate,
           average_heart_rate,
           distance,
           altitude_gain,
           altitude_change,
           wo_len)

stand_runs <- stand_runs %>%
    inner_join(wrun, by = "date")

stand_runs <- stand_runs %>% 
    mutate(score = score * 10, 
           score_differential =  score / mean(score),
           run_by_strain = raw_intensity_score / score_differential,
           run_by_cal = calories / score_differential,
           run_by_hr =  average_heart_rate / score_differential)

mean_run <- ggplot(stand_runs, aes(x = date, y = score_differential)) + 
    geom_hline(yintercept = 1, color = "red") + 
    geom_point() + 
    geom_smooth()

rbs <- ggplot(stand_runs, aes(x = date, y = run_by_strain)) + 
    geom_point() + 
    geom_smooth()

str <- ggplot(stand_runs, aes(x = date, y = raw_intensity_score)) + 
    geom_point() + 
    geom_smooth()

rbc <- ggplot(stand_runs, aes(x = date, y = run_by_cal)) + 
    geom_point() + 
    geom_smooth()

cal <- ggplot(stand_runs, aes(x = date, y = calories)) + 
    geom_point() + 
    geom_smooth()

rbhr <- ggplot(stand_runs, aes(x = date, y = run_by_hr)) + 
    geom_point() + 
    geom_smooth()

hr <- ggplot(stand_runs, aes(x = date, y = average_heart_rate)) + 
    geom_point() + 
    geom_smooth()


grid.arrange(rbs, rbc, rbhr,
             str, cal, hr,
             mean_run, mean_run, mean_run,
             nrow = 3)

plot_data <- stand_runs %>% 
    select(date, 
           run_by_strain,
           run_by_cal,
           run_by_hr) %>% 
    pivot_longer(!date, names_to = "metric", values_to = "rate")

ggplot(plot_data, aes(x = date, y = rate, color = metric)) +
    geom_point() + 
    geom_smooth() + 
    facet_wrap(~ metric, scales = "free")

```

mean_run * differential ~ avg_heart_rate
mean_run ~ avg_heart_rate / differential

score = mean_run * differential
differential = score / mean_run

