---
title: "TDaily Digest - `r format(Sys.time(), '%B %d, %Y %I:%M:%S %p')`"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bootswatch: cosmo
    orientation: rows
    vertical_layout: fill
---

```{r setup, include = FALSE}
# Source Libraries Script
source("01_hkv2_libraries.R")

# Source universal variables
source("00_hkv2_unviersal_variables.R")

# Refresh Data
system("/bin/bash 02_hkv2_data_refresh.sh")

#####################
## GET EVENTS DATA ##
#####################

# Source event data functions
source("03_01_hkv2_event_data_functions.R")

# Get all events from my calendars
events <- get_events_data()
# How many workout windows do I have today?
wo_window_num <- get_wo_windows_num(events)
# What are the workout windows?
wo_windows <- get_wo_windows(events)

######################
## GET WORKOUT DATA ##
######################

source("03_02_hkv2_workout_data_functions.R")
source("03_03_hkv2_cycles_data_functions.R")
source("03_04_hkv2_general_data_functions.R")
source("03_05_hkv2_anomaly_detection_functions.R")

source("04_01_hkv2_table_functions.R")

todays_wo <- get_todays_wo()
todays_status <- get_category_sum_data(get_workout_dates_data(range_start),
                                       NUM_CARDIO,
                                       NUM_MUSCULAR,
                                       NUM_NON,
                                       NUM_RESTORE)
wo_message <- get_wo_message(todays_wo, wo_window_num, wo_windows)

# workouts <- get_workouts_data()
# avg_workout <- get_avg_workouts_data(workouts, TRUE)
# avg_workout_long <- get_avg_workouts_data(workouts)
# todays_workouts <- get_todays_workout_data(workouts)
```

Today
=====================================

Row
-----------------------------------------------------------------------

### Today's Workout: `r todays_wo`.

Today's Workout: `r todays_wo`.

`r wo_message`

### Today's Status

```{r}
todays_status %>% 
    arrange(desc(behind), num_efforts) %>% 
    rename(Category = category,
           Efforts = num_efforts,
           `Behind?` = behind,
           `Last Workout Date` = last_date,
           `Days Since Last` = days_since_last) %>% 
    present_table()
```

### Today's Messages

```{r, results = "asis"}
tracked_measures <- get_tracked_measures()

anom_dat <- tracked_measures %>%
        pmap_dfr(get_anomoly_data) %>%
    filter(((date == Sys.Date() &
               (df == "recovery" |
                    df == "sleep")) |
                (date == Sys.Date() - days(1) &
                     df == "cycles")) &
               (alert_tdt_avg == TRUE |
                    alert_tdt == TRUE |
                    alert_tdt_30 == TRUE |
                    alert_diff_10_week == TRUE )) %>%
    select(date,
           variable,
           message)

if (dim(anom_dat)[1] == 0) {
    anom_mess <- "There are no alerts for today."
} else {
    anom_mess <- paste0("There are ", dim(anom_dat)[1], " alerts for today.")

    for (var in unique(anom_dat$variable)) {
        anom_mess <- paste0(anom_mess, "\n\n- ", var)

        anom_mess <- paste0(anom_mess, "\n\t- ", anom_dat$message[anom_dat$variable == var])

    }
}

cat(anom_mess)
```
